"""
Initial migration. Hand-written rather than autogenerated so the repo has
one canonical migration. Re-running `makemigrations` would produce a more
verbose-but-equivalent file.
"""
import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("default_region", models.CharField(max_length=8, default="GLOBAL")),
                ("default_currency", models.CharField(max_length=3, default="USD")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(max_length=200)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="users", to="core.tenant")),
            ],
            options={"unique_together": {("tenant", "email")}},
        ),
        migrations.CreateModel(
            name="EmissionCategory",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("scope", models.IntegerField(choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")])),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100, blank=True)),
                ("canonical_unit", models.CharField(max_length=20)),
                ("ghg_protocol_code", models.CharField(max_length=20, blank=True)),
            ],
            options={"unique_together": {("scope", "category", "subcategory")}},
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("region", models.CharField(max_length=8, default="GLOBAL")),
                ("unit", models.CharField(max_length=20)),
                ("value_kgco2e_per_unit", models.DecimalField(max_digits=18, decimal_places=8)),
                ("source", models.CharField(max_length=120)),
                ("version", models.CharField(max_length=20, default="1")),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(null=True, blank=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="factors", to="core.emissioncategory")),
            ],
            options={"indexes": [models.Index(fields=["category", "region", "valid_from"], name="core_emissi_categor_idx")]},
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("kind", models.CharField(max_length=40, default="plant")),
                ("region", models.CharField(max_length=8, default="GLOBAL")),
                ("source_codes", models.JSONField(default=dict, blank=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
            ],
            options={"unique_together": {("tenant", "name")}},
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("kind", models.CharField(max_length=40, choices=[
                    ("sap_flatfile", "SAP flat-file export"),
                    ("utility_pdf", "Utility PDF bill"),
                    ("travel_api", "Travel platform API export"),
                ])),
                ("adapter_config", models.JSONField(default=dict, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
            ],
            options={"unique_together": {("tenant", "name")}},
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("file_name", models.CharField(max_length=400, blank=True)),
                ("status", models.CharField(max_length=20, default="pending", choices=[
                    ("pending", "Pending"), ("running", "Running"),
                    ("succeeded", "Succeeded"), ("partial", "Partial — some rows failed"),
                    ("failed", "Failed"),
                ])),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True, blank=True)),
                ("row_count_received", models.IntegerField(default=0)),
                ("row_count_normalized", models.IntegerField(default=0)),
                ("row_count_failed", models.IntegerField(default=0)),
                ("error_log", models.JSONField(default=list, blank=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="core.source")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
                ("triggered_by", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to="core.user")),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("source_row_ref", models.CharField(max_length=200)),
                ("payload", models.JSONField()),
                ("row_hash", models.CharField(max_length=64, db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("ingestion_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="raw_records", to="core.ingestionrun")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="EmissionActivity",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("activity_date", models.DateField()),
                ("period_start", models.DateField(null=True, blank=True)),
                ("period_end", models.DateField(null=True, blank=True)),
                ("quantity_original", models.DecimalField(max_digits=18, decimal_places=6)),
                ("unit_original", models.CharField(max_length=40)),
                ("quantity_normalized", models.DecimalField(max_digits=18, decimal_places=6, null=True, blank=True)),
                ("unit_normalized", models.CharField(max_length=20, blank=True)),
                ("conversion_factor", models.DecimalField(max_digits=18, decimal_places=8, null=True, blank=True)),
                ("factor_value_snapshot", models.DecimalField(max_digits=18, decimal_places=8, null=True, blank=True)),
                ("factor_source_snapshot", models.CharField(max_length=120, blank=True)),
                ("emissions_kgco2e", models.DecimalField(max_digits=18, decimal_places=4, null=True, blank=True)),
                ("status", models.CharField(max_length=20, default="pending", choices=[
                    ("pending", "Pending review"), ("flagged", "Flagged"),
                    ("approved", "Approved"), ("locked", "Locked for audit"),
                    ("superseded", "Superseded by re-ingestion"),
                ])),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(null=True, blank=True)),
                ("locked_at", models.DateTimeField(null=True, blank=True)),
                ("approved_by", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="approved_activities", to="core.user")),
                ("locked_by", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="locked_activities", to="core.user")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="core.emissioncategory")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, null=True, blank=True, related_name="activities", to="core.facility")),
                ("factor", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="activities", to="core.emissionfactor")),
                ("ingestion_run", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="activities", to="core.ingestionrun")),
                ("raw_record", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, null=True, blank=True, related_name="activities", to="core.rawrecord")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="core.source")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
                ("supersedes", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="superseded_by", to="core.emissionactivity")),
                ("adjusts", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="adjusted_by", to="core.emissionactivity")),
            ],
            options={"indexes": [
                models.Index(fields=["tenant", "status"], name="core_act_tenant_status_idx"),
                models.Index(fields=["tenant", "activity_date"], name="core_act_tenant_date_idx"),
                models.Index(fields=["tenant", "source", "status"], name="core_act_tenant_src_st_idx"),
            ]},
        ),
        migrations.CreateModel(
            name="ValidationFlag",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("code", models.CharField(max_length=40, choices=[
                    ("MISSING_FACTOR", "No emission factor matched"),
                    ("UNIT_UNRESOLVED", "Unit not recognized"),
                    ("OUTLIER_VS_PRIOR_PERIOD", "Quantity is far from the recent average"),
                    ("DUPLICATE_SUSPECTED", "Looks like a duplicate of another row"),
                    ("PLANT_CODE_UNMAPPED", "Source code did not match any facility"),
                    ("BILLING_PERIOD_MISALIGNED", "Period spans multiple calendar months"),
                    ("DUPLICATE_OF_LOCKED", "Re-ingested but original row is locked"),
                ])),
                ("severity", models.CharField(max_length=10, default="warn", choices=[("info", "Info"), ("warn", "Warning"), ("error", "Error")])),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed_at", models.DateTimeField(null=True, blank=True)),
                ("dismissal_reason", models.TextField(blank=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="core.emissionactivity")),
                ("dismissed_by", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to="core.user")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("entity_type", models.CharField(max_length=60)),
                ("entity_id", models.UUIDField()),
                ("action", models.CharField(max_length=40)),
                ("before", models.JSONField(default=dict, blank=True)),
                ("after", models.JSONField(default=dict, blank=True)),
                ("reason", models.TextField(blank=True)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to="core.user")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="core.tenant")),
            ],
            options={"indexes": [
                models.Index(fields=["tenant", "entity_type", "entity_id"], name="core_audit_ent_idx"),
                models.Index(fields=["tenant", "ts"], name="core_audit_ts_idx"),
            ]},
        ),
    ]
